#!/bin/bash
# PostCompact hook - runs after context compaction
# Outputs critical rules that must survive compaction

echo "=== CRITICAL RULES (post-compact reload) ==="
echo ""
echo "1. YOUTUBE: Always use Apify: cd automations/youtube && node transcripts.js <url>"
echo "   NEVER use WebFetch for YouTube. NEVER."
echo ""
echo "2. SUB-AGENTS: They start BLANK. Inject context into every agent prompt."
echo "   YouTube agents MUST get the transcripts.js command."
echo ""
echo "3. SKILLS: Check .claude/skills/ before doing anything manually."
echo "   Routing table: .claude/rules/04-skill-routing.md + .claude/reference/registry.md"
echo ""
echo "4. MEMORY: Persist new information to memory/ files IMMEDIATELY. Don't wait."
echo ""
echo "5. CONTENT: No AI smell. Banned words: .claude/skills/voice-check.md"
echo ""
echo "6. QUALITY: Iterate until avg 9+, no dimension < 7. See quality-gate skill."
echo ""
echo "7. COMMANDS: Run all commands yourself. Never tell the owner to run something."
echo ""
echo "8. PUSH: git add -A && git commit && git push origin main after every task."
echo ""
echo "9. GOOGLE: gws CLI only. NEVER use mcp__claude_ai_* Google tools."
echo ""
echo "10. PRIVACY: Never reveal anything on the owner's privacy list (rule 13)."
echo ""
echo "=== Read .claude/rules/*.md and CLAUDE.md for full details ==="
